<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "instituicao".
 *
 * @property integer $id_instituicao
 * @property string $nome
 * @property string $cnpj
 * @property string $descricao
 * @property string $email
 * @property string $telefone
 * @property string $endereco
 * @property string $bairro
 * @property string $cep
 * @property string $login
 * @property string $senha
 * @property string $imagem
 * @property string $video
 * @property integer $perfil
 * @property string $vinculo_api
 *
 * @property Doacao[] $doacaos
 * @property InstituicaoRedeSocial $instituicaoRedeSocial
 */
class Instituicao extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'instituicao';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nome', 'cnpj', 'descricao', 'email', 'telefone', 'endereco', 'bairro', 'cep', 'file'], 'required'],
            [['descricao'], 'string'],
            [['email'], 'email'],
            [['perfil'], 'integer'],
            [['nome', 'cnpj', 'email', 'telefone', 'endereco', 'bairro', 'cep', 'login', 'senha', 'imagem', 'video', 'vinculo_api'], 'string', 'max' => 255],
            [['file'], 'image']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_instituicao' => 'Cód. Instituição',
            'nome' => 'Nome',
            'cnpj' => 'CNPJ',
            'descricao' => 'Descrição',
            'email' => 'E-mail',
            'telefone' => 'Telefone',
            'endereco' => 'Endereço',
            'bairro' => 'Bairro',
            'cep' => 'CEP',
            'login' => 'Login',
            'senha' => 'Senha',
            'imagem' => 'Imagem',
            'file' => 'Imagem',
            'video' => 'Vídeo',
            'perfil' => 'Perfil',
            'vinculo_api' => 'Vínculo com API',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDoacoes()
    {
        return $this->hasMany(Doacao::className(), ['id_instituicao' => 'id_instituicao']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInstituicaoRedeSocial()
    {
        return $this->hasMany(InstituicaoRedeSocial::className(), ['id_instituicao' => 'id_instituicao']);
    }

    public function beforeValidate()
    {
        $this->file = UploadedFile::getInstance($this, 'file');

        if ($this->file) {
            $this->imagem = md5(uniqid() . mt_rand() . microtime()) . '.' . $this->file->getExtension();
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $this->file->saveAs('uploads/' . $this->imagem);

        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
