<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;
use yii\web\UploadedFile;

/**
 * This is the model class for table "resultado".
 *
 * @property int $id_resultado
 * @property int $id_doacao
 * @property string $descricao
 * @property string $data
 * @property string $imagem
 *
 * @property Doacao $doacao
 */
class Resultado extends \yii\db\ActiveRecord
{

    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'resultado';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_doacao', 'descricao', 'data', 'imagem'], 'required'],
            [['id_doacao'], 'integer'],
            [['descricao', 'imagem'], 'string'],
            [['data'], 'date', 'format'=>'dd/MM/yyyy'],
            [['file'], 'image'],
            [['id_doacao'], 'exist', 'skipOnError' => true, 'targetClass' => Doacao::className(), 'targetAttribute' => ['id_doacao' => 'id_doacao']],
            [['imagem'], 'image','extensions' => 'png, jpg, jpeg, gif', 'skipOnEmpty' => true, 'on' => 'update-photo-upload'],
            [['imagem'], 'image','extensions' => 'png, jpg, jpeg, gif', 'skipOnEmpty' => false, 'on' => 'insert-photo-upload']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_resultado' => 'Cód. Resultado',
            'id_doacao' => 'Cód. Doação',
            'descricao' => 'Título',
            'data' => 'Data',
            'imagem' => 'Imagem',
            'file' => 'Imagem'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDoacao()
    {
        return $this->hasOne(Doacao::className(), ['id_doacao' => 'id_doacao']);
    }

    public function beforeValidate()
    {
      $this->file = UploadedFile::getInstance($this, 'file');

      if ($this->file) {
        $this->imagem = md5(uniqid() . mt_rand() . microtime()) . '.' . $this->file->getExtension();
      }

      return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {

      if($insert) {
        if ($this->imagem) {
          $this->file->saveAs('uploads/' . $this->imagem);
        }
      } else {

        if(!empty($changedAttributes['imagem'])) {
          if ($this->imagem) {
            $this->file->saveAs('uploads/' . $this->imagem);
          }
        }
      }

      return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert) {
      if($this->data){

        $dateTime = \DateTime::createFromFormat("d/m/Y", $this->data);
        $this->data = \Yii::$app->formatter->asDatetime($dateTime, "php:Y-m-d");

      }
      return parent::beforeSave($insert);
    }
}
